steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:v2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app:v2']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'update-container', 'nnabuisi-instance', '--container-image', 'gcr.io/$PROJECT_ID/flask-app:v2', '--zone', 'us-central1-c']
images:
- 'gcr.io/$PROJECT_ID/flask-app:v2'
